site_name: Reticence Ji's Notes
site_url: https://reticenceji.github.io
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.path
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.prune
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: Light Mode
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  language: zh
  icon:
    repo: fontawesome/brands/github
  favicon: static/favicon.png
plugins:
  - search
  - tags
  - social
  - meta-descriptions
  - blog:
      blog_dir: 随笔
      blog_toc: true
extra_javascript:
  - https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/mathjax/3.2.0/es5/tex-mml-chtml.js
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
copyright: Copyright &copy; 2024 Reticence Ji
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/reticenceji/reticenceji.github.io  
repo_name: reticenceji/reticenceji.github.io

# 添加社交链接
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reticenceji
      name: Reticence Ji on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/reticenceji
      name: Reticence Ji on LinkedIn

# 如果部署到子目录，需要设置
site_dir: site